# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: pre-commit/action@v3.0.1

    # Run Pre-commit on all files
    # This will auto-run ruff/sqlfluff/check dependencies.
    - name: Run pre-commit
      run: pre-commit run --all-files

    # Install deps with requirements_all.txt
    - name: Install dependencies
      run: |
        python -m pip install -r requirements_all.txt

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    # Run tests
    - name: Test with pytest
      run: |
        python -m pytest
